@echo off
echo Verificare compilare...
if not exist "bin" (
    echo Creare director pentru clase compilate...
    mkdir bin
    echo Compilare...
    javac -d bin src/server/*.java src/client/*.java
)

echo Pornire server admin...
java -cp bin server.ReservationServer 